/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package console;

import console.Console;

public class Tela extends javax.swing.JFrame {

    Console console;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        console = new Console();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ligarConsole = new javax.swing.JButton();
        abrirTampaDeDisco = new javax.swing.JButton();
        memory = new javax.swing.JButton();
        controle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ligar = new javax.swing.JTextField();
        ligar1 = new javax.swing.JTextField();
        tampa = new javax.swing.JTextField();
        MemoryCard = new javax.swing.JTextField();
        ControleTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Playstation 2");

        ligarConsole.setText("Ligar/Desligar");
        ligarConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligarConsoleActionPerformed(evt);
            }
        });

        abrirTampaDeDisco.setText("Abrir Tampa de Disco");
        abrirTampaDeDisco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirTampaDeDiscoActionPerformed(evt);
            }
        });

        memory.setText("Inserir/Tirar Memory");
        memory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryActionPerformed(evt);
            }
        });

        controle.setText("Inserir/Tirar Controle");
        controle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controleActionPerformed(evt);
            }
        });

        ligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligarActionPerformed(evt);
            }
        });

        ligar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ligar1ActionPerformed(evt);
            }
        });

        tampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampaActionPerformed(evt);
            }
        });

        MemoryCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemoryCardActionPerformed(evt);
            }
        });

        ControleTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControleTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(controle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ligarConsole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abrirTampaDeDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ControleTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(MemoryCard)
                            .addComponent(tampa)
                            .addComponent(ligar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(217, 217, 217)
                    .addComponent(ligar1)
                    .addGap(136, 136, 136)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ligarConsole)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(ligar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirTampaDeDisco)
                    .addComponent(jLabel7)
                    .addComponent(tampa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memory)
                    .addComponent(MemoryCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controle)
                    .addComponent(ControleTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 113, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(ligar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void controleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controleActionPerformed
        console.inserirControle();
        if(console.controleUm() == true){
            ControleTexto.setText("Conectado");
        } else {
            ControleTexto.setText("Desconectado");
        }
    }//GEN-LAST:event_controleActionPerformed

    private void ligarConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligarConsoleActionPerformed
        console.ligar();
        if (console.isOn() == true) {
            ligar.setText("ligado");
        } else {
            ligar.setText("desligado");
        }

    }//GEN-LAST:event_ligarConsoleActionPerformed

    private void memoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryActionPerformed
        console.inserirMemoria();
         if (console.memory() == true) {
            MemoryCard.setText("Inserido");
        } else {
            MemoryCard.setText("Removido");
        }
    }//GEN-LAST:event_memoryActionPerformed

    private void ligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ligarActionPerformed

    private void ligar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ligar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ligar1ActionPerformed

    private void MemoryCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemoryCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemoryCardActionPerformed

    private void ControleTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControleTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ControleTextoActionPerformed

    private void tampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampaActionPerformed
        
    }//GEN-LAST:event_tampaActionPerformed

    private void abrirTampaDeDiscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirTampaDeDiscoActionPerformed
         console.abrirTampa();
         if (console.tampaDoDisco() == true) {
            tampa.setText("Aberta");
        } else {
            tampa.setText("Fechada");
        }

    }//GEN-LAST:event_abrirTampaDeDiscoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ControleTexto;
    private javax.swing.JTextField MemoryCard;
    private javax.swing.JButton abrirTampaDeDisco;
    private javax.swing.JButton controle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField ligar;
    private javax.swing.JTextField ligar1;
    private javax.swing.JButton ligarConsole;
    private javax.swing.JButton memory;
    private javax.swing.JTextField tampa;
    // End of variables declaration//GEN-END:variables
}
